DF-2903: Adding business logs to KAE e-mail service.
alv-ch/alv-onlineform-service pull request #149
Opened 2020-09-18 14:39 UTC by seco-mgabor

2020-09-21 07:28 UTC, emina-str commented
@seco-mgabor  the build is failing.

2020-09-21 07:46 UTC, seco-mgabor commented
> @seco-mgabor the build is failing.

Thanks @emina-str. I've seen it. I will take a look together with @palsch later. I just don't know how to convert this to a draft PR.

2020-09-21 12:28 UTC, palsch commented
Bei den Tests kann er den ApplicationContext nicht laden, weil er den BusinessLogger nicht findet. Diesen müsste man entweder mocken oder injecten (@Autowired)

2020-09-21 12:29 UTC, palsch requested changes
tests bitte fixen

2020-09-21 12:30 UTC, seco-mgabor commented on application/src/main/java/ch/admin/seco/alv/service/onlineform/application/kae/logging/BusinessLogEvent.java
> +    KAE_MAIL_SENT_TO_KOFAX("KAE_KOFAX MAIL");
2 eMails werden zugeschickt: einmal an Kofax und ein mal an den Arbeigeber, bzw. PAV.
Habe ich was übersehen?

2020-09-21 13:18 UTC, seco-mgabor commented on application/src/main/java/ch/admin/seco/alv/service/onlineform/application/kae/logging/BusinessLogEvent.java
> +    KAE_MAIL_SENT_TO_KOFAX("KAE_KOFAX MAIL");
Merci :)

2020-09-21 14:29 UTC, emina-str commented
> > @seco-mgabor the build is failing.
> 
> Thanks @emina-str. I've seen it. I will take a look together with @palsch later. I just don't know how to convert this to a draft PR.

@seco-mgabor  Hi, you have to add this lines of code in 
`alv-onlineform-service\application\src\test\java\ch\admin\seco\alv\service\onlineform\TestConfig.java`.

```
	@MockBean
	private CurrentUserContext currentUserContext;

	@MockBean
	BusinessLogger businessLogger;
```

2020-09-22 07:32 UTC, emina-str commented on application/src/main/java/ch/admin/seco/alv/service/onlineform/application/kae/KaeMailApplicationService.java
> +    static final String DEFAULT_RECEIVER_EMAIL_ADDRESS = "kofax@kofax.ch";
@seco-mgabor  why do you add this here if we have default property defined in application.yml
https://github.com/alv-ch/alv-onlineform-service/blob/master/app-onlineform/src/main/resources/application.yml#L102

2020-09-22 07:36 UTC, seco-mgabor commented on application/src/main/java/ch/admin/seco/alv/service/onlineform/application/kae/KaeMailApplicationService.java
> +    static final String DEFAULT_RECEIVER_EMAIL_ADDRESS = "kofax@kofax.ch";
Because otherwise I'll get a NullPointerException in the unit tests. So I had to initialize this field somehow.

2020-09-22 09:51 UTC, emina-str commented on application/src/main/java/ch/admin/seco/alv/service/onlineform/application/kae/KaeMailApplicationService.java
> +    static final String DEFAULT_RECEIVER_EMAIL_ADDRESS = "kofax@kofax.ch";
I was just wondering, isn't it possible to specify it only in the junit test, and not in the implementation?

2020-09-22 09:53 UTC, seco-mgabor commented on application/src/main/java/ch/admin/seco/alv/service/onlineform/application/kae/KaeMailApplicationService.java
> +    static final String DEFAULT_RECEIVER_EMAIL_ADDRESS = "kofax@kofax.ch";
If you take Spring magic away, that field won't be initialised. The other option would have been a set() method, which I didn't find very appropriate for this case.

2020-09-22 11:09 UTC, emina-str approved these changes

2020-09-22 13:42 UTC, palsch commented on application/src/test/java/ch/admin/seco/alv/service/onlineform/application/kae/util/KaeShortValidatorTest.java
> +        kaeDto.setShortTimeWorkTo(tenDaysInFuture.plusMonths(3).plusDays(1).toLocalDate());
This should also fail, if you add only 3 months, without the additional day.
Maybe you can adapt this test to that?

2020-09-22 13:47 UTC, palsch commented on application/src/test/java/ch/admin/seco/alv/service/onlineform/application/kae/KaeMailApplicationServiceTest.java
> +    public void shouldCreateBusinessLogWhenSendMailToCompany() {
Maybe it is possible to make the "given" part more readable. e.g. to set only required test fields and also to group them?

2020-09-22 13:55 UTC, palsch approved these changes

2020-09-23 09:32 UTC, merged